default_environment: dev
environments:
- name: dev
jobs:
- name: tap-csv-to-target-postgres-with-dbt
  tasks:
  - tap-csv target-postgres dbt-postgres:run
- name: tap-shopify-to-target-postgres-with-dbt
  tasks:
  - tap-shopify target-snowflake dbt-snowflake:run
plugins:
  extractors:
  - name: tap-shopify
    variant: singer-io
    pip_url: tap-shopify
    config:
      shop: prescient-test-store
      start_date: '2022-12-01'
    select:
    - collects.*
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      destination_path: output
      do_timestamp_file: true
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    config:
      dbname: gdb
      host: 0.tcp.in.ngrok.io
      port: 14913
      user: admin
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      account: mza63044.us-east-1
      dbname: MELTANO
      file_format: MELTANO.PUBLIC.GFILE
      role: ppw_target_snowflake
      s3_bucket: meltanodatastorageprescientaiio
      stage: MELTANO.PUBLIC.DEVSTAGE
      user: PRESCIENTRAJIV
      warehouse: PRESCIENT_WH
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  transformers:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-postgres~=1.3.0
    config:
      dbname: gdb
      host: 0.tcp.in.ngrok.io
      port: 14913
      schema: tap_csv
      user: admin
  - name: dbt-snowflake
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-snowflake~=1.3.0
    config:
      account: mza63044.us-east-1
      database: MELTANO
      role: ppw_target_snowflake
      schema: tap_shopify
      user: PRESCIENTRAJIV
      warehouse: PRESCIENT_WH
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
project_id: b8ab2bb2-f4d2-4a1b-9930-780326a3237d
schedules:
- name: daily-csv-load
  interval: '@daily'
  job: tap-csv-to-target-postgres-with-dbt
- name: daily-shopify-load
  interval: '@daily'
  job: tap-shopify-to-target-postgres-with-dbt
version: 1
